
# Context

The last assessment for Pacific Cod in British Columbia (BC) was done in 2018, providing catch advice for 2019 [@forrest2020; @dfo2019].
Separate assessments were done for stocks in Area 3CD (West Coast Vancouver Island: WCVI) and Area 5ABCD (Queen Charlotte Sound (QCS) and Hecate Strait (HS) combined) (Figure \@ref(fig:fig-map)).
Both the 3CD and 5ABCD stocks were assessed to be in the Cautious Zone [@dfo2009].

Fishery-independent synoptic bottom trawl surveys are conducted biennially in BC, usually occurring in even-numbered years for WCVI, and odd-numbered years in QCS and HS.
However, due to the COVID-19 pandemic, the scheduled 2020 WCVI survey did not occur.
The 2018 survey index for WCVI was very low, at approximately 25% of the magnitude of the 2014 and 2016 observations (Table \@ref(tab:surv-canadian-table); Figure \@ref(fig:fig-summary-indices-3cd)).
The commercial CPUE index has also decreased since 2016 (Figure \@ref(fig:fig-summary-indices-3cd)).
Catches in 2018 and 2019 in Area 3CD were also much lower than previous years (Table \@ref(tab:tab-catch-3cd), Figure \@ref(fig:fig-catch-3cd)).

The previous advice [@dfo2019] recommended assessment updates in each area be provided in years immediately following the biennial groundfish synoptic bottom trawl survey (i.e., when the most recent survey index point is available).
However, given the low 2018 index of abundance in Area 3CD, coupled with the lack of updated survey information in 2020, Fisheries and Oceans Canada (DFO) Pacifc Fisheries Management Branch has requested that DFO Pacifc Science Branch assess the status of both BC Pacific cod stocks in **2020** and recommend harvest advice for **2021** to inform the development of the 2020/2021 Integrated Fisheries Management Plan.

This Science Response report responds to this request and provides updated stock status advice for Pacific Cod in Areas 3CD and 5ABCD in 2020, and updates catch advice for 2021.

*TODO: currently data only up to 2019. Update to 2020, will have to pro-rate catch.*

# Background

Pacific Cod (or Grey Cod) is a relatively short-lived (~10-13 *y*), fast-growing member of the family Gadidae.
It is distributed throughout the north Pacific Ocean, and throughout the waters of BC, typically in depth ranges up to 200 m. 

Four stocks of Pacific Cod are defined for management purposes on the BC coast: Strait of Georgia (4B); West Coast Vancouver Island (3CD); Queen Charlotte Sound (5AB); and Hecate Strait (5CD). This study focuses on the stocks in Queen Charlotte Sound combined with Hecate Strait (5ABCD), and West Coast Vancouver Island (3CD) (Figure \@ref(fig:fig-map)).

The choice to provide science advice for combined areas 5AB and 5CD in a single stock assessment in 2018 [@dfo2019], and therefore in the current advice, was due mainly to poor model diagnostics and the lack of historical fishery-independent indices of abundance for the Area 5AB model in the 2013 assessment [@forrest2015].
There is also no evidence for genetic distinction between these two stocks [@forrest2015].

# Description of the fishery

Pacific Cod in BC are caught almost entirely in the groundfish bottom trawl fishery, which is part of BC's integrated groundfish fishery [@dfo2017].
They are also caught in small quantities in the groundfish longline fishery (around 0.5% of the total annual catch on average), which is also part of the integrated fishery.
The depth range of capture in 5ABCD ranges from around 60--200 m, with data showing a shift to deeper depths since 1996 [@forrest2020].

Currently, the majority of the BC Pacific Cod catch is taken from HS (Area 5CD).
Commercial catches also come from QCS (Area 5AB) and WCVI (Area 3CD). 
Near negligible catch is taken from the west coast of Haida Gwaii, Area 5E ( < 0.5% of total average annual catch since 1985).

The BC integrated fishery is subject to 100% at-sea and dockside monitoring.
Since 1996, all bottom trawl vessels have carried observers, who record the catch of each species and estimate quantities of released (discarded) fish.
An exception was 
Therefore, since 1996, estimates of catch and at-sea releases can be considered accurate.
For the period 1956--1995 estimates of catch and releases were obtained from fishing logbooks.
Estimates of at-sea releases for this period are likely to be under-estimates [@forrest2020]

# Analysis and response

## Data

Data were extracted from DFO databases in the same way as described in @forrest2020.
The fishing year for all data sources is defined as spanning April 1 to March 31 in the following year [@forrest2015; @forrest2020].
Biological data from fishery-indendent and commercial fishery sources were available up until 2019.
Catch data were updated to 2020, with data extrapolated from October 1, 2020 to March 31, 2021, based on the mean proportion of annual catch caught by September 30 in the three preceding years (the same approach as taken by @forrest2020).

For each area, models were fit to the following data streams: commercial catch data; fishery-independent indices of abundance; commercial catch per unit effort (CPUE); and annual mean weight of fish in the commercial catch.

### Commercial catch

Commercial catch data were extracted from three different databases held by DFO: *GFCatch* (Canadian trawl landings, 1954--1995); *PacHarvTrawl* (Canadian trawl landings, 1996 to March 31, 2007); and *GFFOS* (Canadian trawl landings, April 1, 2007 to 2020).
Catch data prior to 1981 include catch by US vessels [@forrest2015; @forrest2020].
Fishing years are defined as beginning on April 1 for all years, and are referenced by starting year, e.g., fishing year 1957 runs from April 1, 1957 to March 31, 1958 [see @forrest2020].

At the time of the assessment, the 2020 fishing year was incomplete.
In order to provide projections for the 2021 fishing season, the 2020 catch was extrapolated in each area, using the three year average proportion of catch taken by September 30 (representing the end of the second quarter of the 2020 fishing year).
This proportion was used to extrapolate from the catch at September 30, 2020 to a total estimated catch for the 2020 fishing year (Tables \@ref(tab:tab-catch-3cd) and \@ref(tab:tab-catch-5abcd)).

### Fishery-independent indices of abundance

#### Canadian bottom trawl surveys

All survey indices were calculated using a swept area analysis, documented in Appendix A of @forrest2020.
Values are provided in Table \@ref(tab:surv-canadian-table) and Figure (fig:surv-canadian).

Abundance in Area 3CD (\@ref(fig:fig-map)) is indexed by the West Coast Vancouver Island Synoptic Survey.
The survey was first conducted in 2004 and is conducted in alternating (even-numbered) years.
Due to the COVID-19 pandemic there was no survey in 2020.

Abundance in Area 5AB (\@ref(fig:fig-map)) is indexed by the Queen Charlotte Sound Synoptic Survey.
The survey was first conducted in 2003 and 2004, and then in odd years since 2005.
Abundance in Area 5CD (\@ref(fig:fig-map)) was indexed by the Hecate Strait Multispecies Assemblage Survey in 1984, 1987, 1989, 1991, 1993, 1995, 1996, 1998, 2000, 2002, and 2003.
Since 2005, it has been indexed in odd-numbered years by the Hecate Strait Synoptic Survey.

Details on spatial extent and depth strata of all surveys are provided in Appendix A of @forrest2020.

#### NMFS Triennial Survey (in Canadian waters)

An additional relative abundance index for Area 3CD was developed using data from the
National Marine Fisheries Service (NMFS) Triennial survey, which operated off the lower half of West Coast Vancouver Island between 1980 and 2001 (Figure \@ref(fig:tri-fig9)).
See Appendix A of @forrest2018 for complete details.

### Commercial CPUE

Standardized commercial CPUE indices were developed for the historical (1956:1995) and modern (1996:2019) periods (Figures  \@ref(fig:cpue-index-ts-hist) and \@ref(fig:cpue-index-ts-modern)).
The indices were developed using a Tweedie standardized generalized linear mixed model (GLMM) described in detail in Appendix B of @forrest2020.
The full standardization historical period GLMMs included predictors for depth, locality, month, and a locality-year interaction (Figure \@ref(fig:cpue-index-ts-hist)).
The full standardization modern period GLMMs included predictors for depth, latitude, locality, month, vessel and a locality-year interaction (Figure \@ref(fig:cpue-index-ts-modern)).

### Annual mean weight in commercial catch

Annual mean weight in the commercial catch was calculated using the methodology decribed in Appendix C of @forrest2020.
Commercial biological samples were available for calculating mean weight from 1956 to 2019.
In the absence of commercial biological samples for 2020, we assumed the same annual mean weight in 2020 as for 2019.

## Stock assessment model

The current stock assessment model is a Bayesian delay-difference model [@deriso1980], fit to survey indices, commercial catch-per-unit-effort (CPUE), commercial catch data and commercial annual mean weights [@forrest2015; @forrest2020].
A full stock assessment history for both stocks is provided in @forrest2020.
The current model is fully described in Appendix D of @forrest2020.
All fixed parameters and prior probability distributions for model parameters in the current assessment were the same as those reported in @forrest2020.

For both areas, the joint posterior distribution for each model was numerically approximated using the Markov Chain Monte Carlo (MCMC) routines built into AD Model Builder (Metropolis-Hastings algorithm) [@fournier2012]. 
Posterior samples were drawn every 1,000 iterations from a chain of length 2 million, resulting in 2,000 posterior samples (the first 1,000 samples were dropped to allow for sufficient burn-in).

@forrest2015 and @forrest2020 used a model-averaging approach to construct decision tables based on combined posterior samples from several different sensitivity cases.
This was to address some of the key irresolvable uncertainties associated with the stock assessment.
Major axes of uncertainty were: catchability ($q$) in the indices of abundance; the magnitude of natural mortality ($M$); age at recruitment to the fishery; and the magnitude of observation errors in the surveys and mean weight [@forrest2020].
Other stock assessments that have used a model-averaging approach are Pacific Hake [@stewart2011], Pacific Halibut [@stewart2016], BC Shortspine Thornyhead [@starr2017] and BC Walleye Pollock [@starr2018]).

## Reference points

The DFO Fishery Decision-making Framework Incorporating the Precautionary Approach (PA) policy [@dfo2009] requires stock status to be characterized using three reference points:

1. A Reference Removal Rate;
2. A Limit Reference Point (LRP);
3. An Upper Stock Reference point (USR).

As in the 2018 assessment [@dfo2019], historical reference points were used to assess stock status, where

1. $\textrm{USR}$ (Upper Stock Reference) is the historical mean of the biomass estimates from 1956--2004.

2. $\textrm{LRP}$ (Limit Reference Point) is the lowest estimated biomass agreed upon as an undesirable state to be avoided. For Area 5ABCD this is the estimated biomass in 2000. For Area 3CD it is the estimated biomass in 1986.

3. $\textrm{LRR}$ (Limit Removal Rate) is the average fishing mortality rate from 1956--2004.

See @forrest2020 for details on the choice to use historical reference points for Pacific Cod.
See also @forrest2018 for simulation-testing of historical reference points for the 5CD stock of Pacific Cod.

## Model scenarios

Reference case models were established for Areas 3CD and 5ABCD to show model response under what were considered the most plausible choices across a range of assumptions for each stock.
The Reference models for Areas 3CD and 5ABCD shared similar characteristics in terms of data choices, prior probability distributions and fixed parameter settings [see @forrest2020].
These models served as the basis from which sensitivity scenarios were developed, altering alternative model assumptions one step at a time.
The same model scenarios as those agreed upon for the 2018 assessment (@dfo2019) were used here for model-averaging (updated with catch data to 2020) .
Full details on the model configurations and assumptions for each scenario are provided in @forrest2020.

### Area 3CD

For Area 3CD, the scenarios (Sc) included in the model-averaging set were:

1.	Sc 1a Reference model
2.	Sc 2d Set the mean of the prior probability distribution for synoptic survey $\ln(q)$ = $\ln(1.0)$
3.	Sc 2e Increase the standard deviation (SD) for synoptic survey $\ln(q)$ to 0.6.
4.	Sc 3a Set the parameters of the prior probability distribution for $\ln(M)$ to $\mathcal{N}\sim(0.4,0.1)$;
5.	Sc 5a Set knife-edged age at recruitment = 3 years
6.	Sc 6b Reduce the overall observation error term $\sigma_O = 0.15$
7.	Sc 7b Reduce the SD in the likelihood for the fit to average annual mean weight $\sigma_W = 0.15$

### Area 5ABCD

For Area 5ABCD, the scenarios included in the model-averaging set were:

1.	Sc 1a Reference model
2.	Sc 2d Set the mean of the prior probability distribution for synoptic surveys $\ln(q)$ = $\ln(1.0)$ (pro-rated by depth-stratum areas of Area 5AB and 5CD)
3.	Sc 2e Increase the standard deviation (SD) for synoptic survey $\ln(q)$ to 0.6.
4.	Sc 3a Set the parameters of the prior probability distribution for $\ln(M)$ to $\mathcal{N}\sim(0.4,0.1)$;
5.	Sc 5a Set knife-edged age at recruitment = 3 years
6.	Sc 6b Reduce the overall observation error term $\sigma_O = 0.15$
7.	Sc 7b Reduce the SD in the likelihood for the fit to average annual mean weight $\sigma_W = 0.15$

## Assessment results {#sec:summary-results}

### Reference model fits to data

#### Area 3CD

Reference case model fits to the data were typical of all sensitivity cases.
The model diagnostics were consistent with convergence and posterior sample autocorrelation was minor for most parameters.
Model fits to the catch were near perfect by design (standard deviation in log likelihood was set to 0.05) and are not shown.

The model fit the two fishery-independent indices (Figure \@ref(fig:fig-base-index-fits-3cd) a and d), but did not closely fit the 2012--2016 data points in the West Coast Vancouver Island Synoptic Survey.
This is likely because of large differences between low points (2012 and 2018) and high points (2014 and 2016) in the survey observations.
Similarly, while the model closely followed the major patterns in the historical CPUE index (Figure \@ref(fig:fig-base-index-fits-3cd) b), it did not capture all the peaks in the modern series (Figure \@ref(fig:fig-base-index-fits-3cd) c).
Fits such as this tend to occur when there is no other information (such as age composition data or contrasting mean weight data) to help resolve large fluctuations in observed indices.

As in the 2018  assessment [@forrest2020], the model tended to underestimate annual mean weight, especially in the early part of the time series (Figure \@ref(fig:fig-base-mean-weight-3cd)).
This is most likely due to most of the length measurements in this part of the time series coming from fish classified as "keepers", i.e., not released at sea (see @forrest2015 for discussion of this issue for the Area 5AB and 5CD stocks).
Smaller, released fish are therefore likely underrepresented in the annual mean weight data prior to the introduction of at-sea observers in 1996.


<!--
Posterior estimated biomass from the reference case model is shown in Figure \@ref(fig:fig-base-biomass-3cd).
Posterior relative biomass from the reference case model is shown in Figure \@ref(fig:fig-base-depl-3cd).
Posterior estimated recruitment and recruitment anomalies from the reference case model are shown in Figure \@ref(fig:fig-base-recr-3cd).
Posterior estimated fishing mortality from the reference case model are shown in Figure \@ref(fig:fig-base-f-3cd).
Median estimated fishing mortality in **2020** was estimated to be very low, at 0.01 *y*^-1^ (Table \@ref(tab:tab-ref-points-table-avg-3cd)).
-->

*TODO: update results once catch is updated. Add comment on convergence*

#### Area 5ABCD

As for Area 3CD, reference case model fits to the data were typical of all sensitivity cases, model diagnostics were consistent with convergence, and posterior sample autocorrelation was minor for most parameters.

*TODO: discuss model fits and convergence*

<!--
Posterior estimated biomass from the reference case model is shown in Figure \@ref(fig:fig-base-biomass-5abcd).
Posterior relative biomass from the reference case model is shown in Figure \@ref(fig:fig-base-depl-5abcd).
Posterior estimated recruitment and recruitment anomalies from the reference case model are shown in Figure \@ref(fig:fig-base-recr-5abcd).
Posterior estimated fishing mortality from the reference case model are shown in Figure \@ref(fig:fig-base-f-5abcd).

-->

### Model-averaged results

#### Area 3CD



Posterior estimated biomass from the seven models used for model-averaging is shown in Figure \@ref(fig:fig-model-average-biomass-comp-3cd).
Combined average biomass for all seven models is shown in Figure \@ref(fig:fig-model-average-biomass-3cd).
Recent average biomass from the seven averaged models with a one year projection under four alternative catch levels is shown in Figure \@ref(fig:fig-model-average-biomass-3cd-proj).

The **2022 biomass is projected to be in the Cautious Zone (below the USR) with greater than 99% probability under all 2021** catch scenarios tested, including zero catch.

#### Area 5ABCD

Posterior estimated biomass from the seven models used for model-averaging is shown in Figure \@ref(fig:fig-model-average-biomass-comp-5abcd).
Combined average biomass for all seven models is shown in Figure \@ref(fig:fig-model-average-biomass-5abcd).
Recent average biomass from the seven averaged models with a one year projection under four alternative catch levels is shown in Figure \@ref(fig:fig-model-average-biomass-5abcd-proj).

Median estimated fishing mortality in *2020* was estimated to be 0.03 y^-1^ (Table \@ref(tab:tab-ref-points-table-avg-5abcd)). 

## Sources of uncertainty


## Conclusions and advice

### Area 3CD

The model-averaged decision table for Area 5ABCD, based on a one year projection over a range of 2020 catch levels, suggests that under a **2021 catch of 950 tonnes (the 2018/19 TAC), there is less than 1% probability that biomass in 2021 will be below the LRP (Table \@ref(tab:summary-tab-decision-avg-5abcd)).**
**Assuming the 2021 catch is of a similar magnitude to the 2018 and 2019 catches (254 and 450 tonnes, respectively), the probability of the 2022 biomass being below the LRP is also less than 1% (Table \@ref(tab:summary-tab-decision-avg-5abcd)).**
**However, the 2023 biomass is projected to be in the Cautious Zone (below the USR) with greater than 99% probability under all 2021 catch scenarios tested, including zero catch.**

### Area 5ABCD

The model-averaged decision table for Area 3CD, based on a one year projection over a range of **2021** catch levels, suggests that under a **2021 catch of 500 tonnes (the 2019/20 TAC), there is a 9% probability that biomass in 2021 will be below the LRP (Table \@ref(tab:summary-tab-decision-avg-3cd))**.
**However, assuming the 2021 catch is of a similar magnitude to the 2018 and 2019 catches (23 and 43 tonnes, respectively), the probability of the 2021 biomass being below the LRP is between 5% and 6% (Table \@ref(tab:summary-tab-decision-avg-3cd)).**

*TODO*

* Re-assessment interval ... as soon as next survey is done

\clearpage
