\clearpage

# Tables {#sec:tables}

```{r tab-catch-3cd}
catch.table(catch.3,
            catch.3.discards,
            area = "3CD",
cap = paste0("Prises déclarées (tm) de morue du Pacifique dans la zone 3CD ",
              "par le Canada et les États-Unis,",
              min(catch.3$year), "--", max(catch.3$year),
              ". Les rejets déclarés pour la période ", min(catch.3$year),
              "--1995 ne sont ",
              "pas représentatives des rejets réels parce que les estimations ont été tirées ",
              "des journaux de bord. Les estimations des rejets depuis 1996 sont fondées sur les ",
              "observations en mer et sont considérées comme plus représentatives des rejets réels."),   french=french)
```

\clearpage

```{r tab-catch-5abcd}
catch.table(catch.5,
            catch.5.discards,
            area = "5ABCD",
cap = paste0("Prises déclarées (tm) de morue du Pacifique dans la zone 5ABCD ",
              "par le Canada et les États-Unis,",
              min(catch.5$year), "--", max(catch.5$year),
              ". Les rejets déclarés pour la période ", min(catch.5$year),
              "--1995 ne sont ",
              "pas représentatives des rejets réels parce que les estimations ont été tirées ",
              "des journaux de bord. Les estimations des rejets depuis 1996 sont fondées sur les ",
              "observations en mer et sont considérées comme plus représentatives des rejets réels."),
              french=french)
```

\clearpage

```{r surv-canadian-table, results='asis'}
dplyr::filter(dat$survey_index, survey_abbrev %in%
  c("SYN QCS", "SYN WCVI", "SYN HS", "SYN WCHG", "OTHER HS MSA")) %>%
  dplyr::select(survey_abbrev, year, biomass, re, lowerci, upperci, num_sets, num_pos_sets) %>%
  dplyr::mutate(lowerci = round(lowerci/1000, 1), upperci = round(upperci/1000, 1),
    biomass = round(biomass/1000, 1), re = round(re, 2)) %>%
  dplyr::rename(`Survey abbrev.` = survey_abbrev, Year = year, Biomass = biomass,
    CV = re, `Lower CI` = lowerci, `Upper CI` = upperci, Sets = num_sets, `Positive sets` = num_pos_sets) %>%
  dplyr::arrange(`Survey abbrev.`, Year) %>%
  dplyr::rename('Relevé' = `Survey abbrev.`, 'Anneé' = Year, Biomasse = Biomass,
    `IC inf.` = `Lower CI`, `IC sup.` =`Upper CI`, Traits = Sets, `Traits  positifs` = `Positive sets` ) %>% 
  knitr::kable(caption = "Données des relevés au chalut sur la morue du Pacifique au Canada. La biomasse relative et les intervalles de confiance (IC) inférieurs et supérieurs correspondants sont indiqués en tonnes métriques (sans tenir compte de la capturabilité du relevé). Les traits positifs désignent le nombre de traits de chalut qui ont capturé des morues du Pacifique.", booktabs = TRUE, linesep = "", 
    format = "pandoc")
```

\clearpage

```{r tab-param-est-table-3cd, results='asis'}
pars_est_omit <- c("$\\overline{R}_{init}$", "$\\overline{R}$", "$\\vartheta$")
make.parameters.est.table(base.model.3cd,
  caption = paste0("Posterior (2.5\\textsuperscript{th} percentile, Median, and ",
    "97.5\\textsuperscript{th} percentile) and MPD ",
    "estimates of key parameters from the Reference Case, Area 3CD. $R_0$ is in thousands of fish. $B_0$ is in tonnes. $\\hat{R}$ is the potential scale reduction statistic and $n_\\mathrm{eff}$ is the effective number of simulation draws (see text). ",
    q.3cd.desc),
  omit_pars = pars_est_omit)
```

```{r tab-param-est-table-5abcd, results='asis'}
pars_est_omit <- c("$\\overline{R}_{init}$", "$\\overline{R}$", "$\\vartheta$")
make.parameters.est.table(base.model.5abcd,
  caption = paste0("Posterior (2.5\\textsuperscript{th} percentile, Median, and ",
    "97.5\\textsuperscript{th} percentile) and MPD ",
    "estimates of key parameters from the Reference Case, Area 5ABCD. $R_0$ is in thousands of fish. $B_0$ is in tonnes. $\\hat{R}$ is the potential scale reduction statistic and $n_\\mathrm{eff}$ is the effective number of simulation draws (see text). ",
    q.5abcd.desc),
  omit_pars = pars_est_omit)
```

\clearpage

```{r tab-ref-points-table-avg-3cd, results='asis'}
make.ref.points.table(c(base.model.3cd,
                        sens.models.13.sub),
                      lrp = 1986,
                      usr = 1956:2004,
                      digits = 2,
                      caption = paste0("Posterior (2.5\\textsuperscript{th} percentile, Median, and ",
                                       "97.5\\textsuperscript{th} percentile) of reference points for ",
                                       "model-averaged Area 3CD. ",
                                       "Biomass is in tonnes."))
```


```{r tab-ref-points-table-avg-5abcd, results='asis'}
make.ref.points.table(c(base.model.5abcd,
                        sens.models.6.sub),
                      lrp = 2000,
                      usr = 1956:2004,
                      digits = 2,
                      caption = paste0("Posterior (2.5\\textsuperscript{th} percentile, Median, and ",
                                       "97.5\\textsuperscript{th} percentile) of reference points for ",
                                       "model-averaged Area 5ABCD. ",
                                       "Biomass is in tonnes."))
```

\clearpage

```{r summary-tab-decision-avg-3cd, results='asis'}
 decision.table(avg.model.3cd,
                caption = paste0("Decision table with model averaging for Area 3CD. Models averaged are: ",
                                 and.string(c(base.model.3cd.name, sens.models.name.13.sub)),
                                 ".", french=french)) #
```


\clearpage

```{r summary-tab-decision-avg-5abcd, results='asis'}
 decision.table(avg.model.5abcd,
                caption = paste0("Decision table with model averaging for Area 5ABCD. Models averaged are: ",
                                 and.string(c(base.model.5abcd.name, sens.models.name.6.sub)),
                                 ".", french=french)) #
```

\clearpage
