\clearpage

# Tables {#sec:tables}

```{r tab-catch-3cd}
catch.table(catch.3,
            catch.3.discards,
            pre.1996.discards.3cd,
            area = "3CD",
 cap = paste0("Prises déclarées (tm) de morue du Pacifique dans la zone 5ABCD ",
              "par le Canada et les États-Unis, ",
              min(catch.3$year)+3, "--", max(catch.3$year),
              ". Les rejets déclarés pour la période ", min(catch.3$year)+3,
              "--1995 ne sont ",
              "pas représentatives des rejets réels parce que les estimations ont été tirées ",
              "des journaux de bord. Les estimations des rejets depuis 1996 sont fondées sur les ",
              "observations en mer et sont considérées comme plus représentatives des rejets réels. The 2020 total catch estimate is extrapolated from the combined landings plus discards taken up to September 30, 2020 (see text). Therefore 2020 nominal landings and discards are not shown individually. Numbers are rounded for presentation."), french=french)
```

\clearpage

```{r tab-catch-5abcd}
catch.table(catch.5,
            catch.5.discards,
            pre.1996.discards.5abcd,
            area = "5ABCD",
 cap = paste0("Prises déclarées (tm) de morue du Pacifique dans la zone 5ABCD ",
              "par le Canada et les États-Unis, ",
              min(catch.5$year)+3, "--", max(catch.5$year),
              ". Les rejets déclarés pour la période ", min(catch.5$year)+3,
              "--1995 ne sont ",
              "pas représentatives des rejets réels parce que les estimations ont été tirées ",
              "des journaux de bord. Les estimations des rejets depuis 1996 sont fondées sur les ",
              "observations en mer et sont considérées comme plus représentatives des rejets réels.  The 2020 total catch estimate is extrapolated from the combined landings plus discards taken up to September 30, 2020 (see text). Therefore 2020 nominal landings and discards are not shown individually. Numbers are rounded for presentation."),      french=french)

```

\clearpage

```{r surv-canadian-table, results='asis'}
dplyr::filter(dat$survey_index, survey_abbrev %in%
  c("SYN QCS", "SYN WCVI", "SYN HS", "OTHER HS MSA")) %>%
  dplyr::select(survey_abbrev, year, biomass, re, lowerci, upperci, num_sets, num_pos_sets) %>%
  dplyr::mutate(lowerci = round(lowerci/1000, 1), upperci = round(upperci/1000, 1),
    biomass = round(biomass/1000, 1), re = round(re, 2)) %>%
  dplyr::rename(`Survey abbrev.` = survey_abbrev, Year = year, Biomass = biomass,
    CV = re, `Lower CI` = lowerci, `Upper CI` = upperci, Sets = num_sets, `Positive sets` = num_pos_sets) %>%
  dplyr::arrange(`Survey abbrev.`, Year) %>%
  dplyr::rename('Relevé' = `Survey abbrev.`, 'Anneé' = Year, Biomasse = Biomass,
    `IC inf.` = `Lower CI`, `IC sup.` =`Upper CI`, Traits = Sets, `Traits  positifs` = `Positive sets` ) %>% 
  knitr::kable(caption = "Données des relevés au chalut sur la morue du Pacifique au Canada. La biomasse relative et les intervalles de confiance (IC) inférieurs et supérieurs correspondants sont indiqués en tonnes métriques (sans tenir compte de la capturabilité du relevé). Les traits positifs désignent le nombre de traits de chalut qui ont capturé des morues du Pacifique.", booktabs = TRUE, linesep = "", 
    format = "pandoc")
```

\clearpage

```{r tab-param-table-3cd, results='asis'}
make.parameters.table(base.model.3cd,
  caption = paste0("Paramètres estimés et fixes et distributions de probabilité a priori utilisés ",
    "dans le scénario de référence, zone 3CD. The survey catchability parameter for WCVI ($q_1$) was estimated with the prior probability distribution $\\textrm{Normal}(ln(0.228),0.3)$. The other survey catchability parameters were estimated without priors."),
  omit_pars = c("Log initial recruitment ($\\ln(\\overline{R}_{init})$)",
    "Log mean recruitment ($\\ln(\\overline{R})$)"),
  omit_selectivity_pars = TRUE, french=french)
```


```{r tab-param-table-5abcd, results='asis'}
make.parameters.table(base.model.5abcd,
  caption = paste0("Paramètres estimés et fixes et distributions de probabilité a priori utilisés ",
    "dans le scénario de référence, zone 5ABCD. The survey catchability parameters for QCS and HS ($q_2$ and $q_3$) were estimated with the prior probability distributions $\\textrm{Normal}(ln(0.408),0.3)$ and $\\textrm{Normal}(ln(0.0654,),0.3)$, respectively. The other survey catchability parameters were estimated without priors."),
  omit_pars = c("Log initial recruitment ($\\ln(\\overline{R}_{init})$)",
    "Log mean recruitment ($\\ln(\\overline{R})$)"),
  omit_selectivity_pars = TRUE, french=french)
```

\clearpage

```{r tab-param-est-table-3cd, results='asis'}
pars_est_omit <- c("$\\overline{R}_{init}$", "$\\overline{R}$", "$\\vartheta$","$B_0$")
make.parameters.est.table(base.model.3cd,
  caption = paste0("Valeur a posteriori (centile 2.5\\textsuperscript{th}, médiane et ",
    "centile 97.5 \\textsuperscript{th}) et estimations de la DPM ",
    "estimations des paramètres clés du scénario de référence, zone 3CD. $R_0$ est en milliers de poissons. $\\hat{R}$ is the potential scale reduction statistic and $n_\\mathrm{eff}$ is the effective number of simulation draws (see text). ",
    q.3cd.desc),
  omit_pars = pars_est_omit, french=french)
```

```{r tab-param-est-table-5abcd, results='asis'}
pars_est_omit <- c("$\\overline{R}_{init}$", "$\\overline{R}$", "$\\vartheta$", "$B_0$")
make.parameters.est.table(base.model.5abcd,
  caption = paste0("Valeur a posteriori (centile 2.5\\textsuperscript{th}, médiane et ",
    "centile 97.5 \\textsuperscript{th}) et estimations de la DPM ",
    "estimations des paramètres clés du scénario de référence, zone 5ABCD. $R_0$ est en milliers de poissons. $\\hat{R}$ is the potential scale reduction statistic and $n_\\mathrm{eff}$ is the effective number of simulation draws (see text). ",
    q.5abcd.desc),
  omit_pars = pars_est_omit, french=french)
```

\clearpage

```{r tab-ref-points-table-avg-3cd, results='asis'}
make.ref.points.table(c(base.model.3cd,
                        sens.models.13.sub),
                        lrr_range = 1956:2004,
                        lrp_range = 1986,
                        usr_range = 1956:2004,
                        digits = 2,
                        caption = paste0("Valeur a posteriori (centile 2,5\\textsuperscript{th} , Median, and centile 97,5\\textsuperscript{th}  ",
                                       ") des points de référence pour la zone 3CD. ",
                                       "La biomasse est en tonnes. All values are rounded. Ratios were calculated using full posterior distributions and cannot be calculated directly from the table."), french=french)
```


```{r tab-ref-points-table-avg-5abcd, results='asis'}
make.ref.points.table(c(base.model.5abcd,
                        sens.models.6.sub),
                        lrr_range = 1956:2004,
                        lrp_range = 2000,
                        usr_range = 1956:2004,
                        digits = 2,
                        caption = paste0("Valeur a posteriori (centile 2,5\\textsuperscript{th} , Median, and centile 97,5\\textsuperscript{th}  ",
                                       ") des points de référence pour la zone 5ABCD. ",
                                       "La biomasse est en tonnes. All values are rounded. Ratios were calculated using full posterior distributions and cannot be calculated directly from the table."), french=french)
```

\clearpage

```{r summary-tab-decision-avg-3cd, results='asis'}
 decision.table(avg.model.3cd,
                caption = paste0("Tableau de décision avec moyenne des modèles pour la zone 3CD."), french=french) #
```


\clearpage

```{r summary-tab-decision-avg-5abcd, results='asis'}
 decision.table(avg.model.5abcd,
                caption = paste0("Tableau de décision avec moyenne des modèles pour la zone 5ABCD."), french=french) #
```

\clearpage
